### ISSUE TITLE
sample.txt missing from Chapter 3 code

### ISSUE THREAD

**Issue by shane-kercheval** [rsharankumar/R_Data_Science_Essentials#1]
Page 55 of book (and `line 81` of code (https://github.com/rsharankumar/R_Data_Science_Essentials/blob/master/Chapter%203/rCode/B04750_Rcode_C3.R))

refer to a `sample.txt`, which I do not see.

**Comment by rsharankumar** [comment]
[sample.txt](https://github.com/rsharankumar/R_Data_Science_Essentials/files/412672/sample.txt)
